server:
  port: 3356
spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/core_banking
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop